### ISSUE TITLE
Just want to get in touch with you.

### ISSUE THREAD

**Issue by Awesomewsdm** [bryanyi/siramiks-OrderService#1]
Hi Bryan. Trust you're well.  

My name is Wisdom Kordah. A Mobile App Developer (Flutter & Dart) from Ghana and a final year student in college. 

I have been following you for a while now since the fall of 2022 and your journey to becoming a Software Engineer interests me a lot. I had like to follow in your steps after completing college. Please is there any way I could get in touch with you?

**Comment by bryanyi** [comment]
Hi there!
Very nice to meet you Wisdom. You can connect with me on LinkedIn or email me at bryanyi1206@gmail.com

Here's my LinkedIn link:
https://www.linkedin.com/in/bryantaeyi/

**Comment by Awesomewsdm** [comment]
Ok. Thank you sir
